### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VoR0220**
Include installation requirements for boost and an easy install for boost for Ubuntu 14.04 LTS users.

### CODE REVIEW

**Comment by vikramrajkumar** [comment]
@VoR0220 Maybe these should go in the Ubuntu build page here: https://github.com/cryptonomex/graphene/wiki/build-ubuntu and in the README we can just put a link to that page?

**Comment by vikramrajkumar** [comment]
Eventually we should have separate build instructions for each OS like in original BTS: https://github.com/bitshares/bitshares#building

**Comment by VoR0220** [comment]
alright, why not then create a link to it in the README? 

I'd be more than happy to update the Ubuntu build page, as I found those instructions to be a little...confusing.

**Comment by vikramrajkumar** [comment]
Feel free to edit this PR to just add a link to the README. And I think you should be able to directly edit the Ubuntu page in the Wiki.

**Pull request closed without merging**
